### ISSUE TITLE
Support for Alert Provisioning API

### ISSUE THREAD

**Issue by haileymoon** [panodata/grafana-client#30]
Hi, i just wanted to know if any support for alerting provisioning api is planned?
or is there any library suggestions for workaround where i can make/update alerting rules by code?

reference:
https://grafana.com/docs/grafana/latest/developers/http_api/alerting_provisioning/

Thanks!

**Comment by amotl** [comment]
Dear @haileymoon,

this API is probably the underpinning for the [new unified alerting system], right?

The API looks extensive, and I am personally short on time, so it would be very sweet to see contributions from the community in this area. I will be happy to share some ideas around it.

With kind regards,
Andreas.

[new unified alerting system]: https://grafana.com/blog/2021/06/14/the-new-unified-alerting-system-for-grafana-everything-you-need-to-know/

**Comment by bursztyn-pl** [comment]
Hello there,

I will need this api to be working, so that I've started working on extending grafana-client. I just wrote class with functions to all alerting provisioning api endpoints. Right now I'll test it and I'll write tests. When finished I'd like to share

**Comment by amotl** [comment]
Sweet. Your contribution will be very much appreciated.

On 17 August 2022 15:05:25 CEST, bursztyn-pl ***@***.***> wrote:
>Hello there,
>
>I will need this api to be working, so that I've started working on extending grafana-client. I just wrote class with functions to all alerting provisioning api endpoints. Right now I'll test it and I'll write tests. When finished I'd like to share
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/panodata/grafana-client/issues/30#issuecomment-1217984747
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
-- 
Sent from my mind. This might have been typed on a mobile device, so please excuse my brevity.

**Comment by amotl** [comment]
Dear @bursztyn-pl,

> I've started working on extending grafana-client. I just wrote class with functions to all alerting provisioning api endpoints. Right now I'll test it and I'll write tests. When finished I'd like to share.

Thank you again for your upcoming contribution.

May I ask if you can share a preview of your working branch for early review? This would make it possible for others to support your work early in the process. If you wish, someone from the community could even take over refining that feature.

With kind regards,
Andreas.

**Comment by bursztyn-pl** [comment]
Hi, let me back to work tomorrow morning, I’lol try to share it. it will be my first contribution to github, so that I need to learn it first. btw, I haven’t done any more tests, code is working as I did „manual tests” in my script and grafana, anyone who want to wrote tests is more than welcome :)

**Comment by sgowris2** [comment]
Hi @bursztyn-pl , I am also in need of this feature and would love to contribute to it in any way. Please add an early version of your code as a branch and let us know which areas are still open to be picked up by others (just so that we don't replicate work). Would really appreciate this!

**Comment by amotl** [comment]
Hi @bursztyn-pl,

thanks for your contribution #41, I've just merged it. @haileymoon and @sgowris2: Feel free to evaluate the implementation, and to submit additional patches if you see room for improvements.

With  kind regards,
Andreas.

**Comment by jyepesr1** [comment]
Hey Guys! any updates on this feature? I would really like to use it.

is it planned for the next release?

Thanks

**Comment by amotl** [comment]
Hi Johan Sebastian,

I haven't had the chance to verify the implementation #41 by @bursztyn-pl, so I hoped that @sgowris2 might give us some feedback about it. If you think it will work, I can run another release. On the other hand, I would be more confident if maybe _you_ could evaluate it and give some feedback about it?

With kind regards,
Andreas.

**Comment by jyepesr1** [comment]
Hi @amotl, for sure! I will test the main branch with those changes and let you know if everything works as expected.

**Comment by jyepesr1** [comment]
I just tested the get and create for alert rules, contact points, and notification policies, endpoints are working as expected, but when we run the get with a non-existing uid, it returns 500 instead of a 404, I checked the API and it produces 404, not sure why those functions return 500.

**Comment by amotl** [comment]
Hi Johan Sebastian,

thanks a stack for your feedback. Can you share some of the code used for testing, in order to make it easier for me to investigate this?

With kind regards,
Andreas.

**Comment by jyepesr1** [comment]
sure! those are my tests. I have three functions and I'm passing the corresponding json models

```python
    def import_alerts(self, filepath: str) -> None:
        f = open(filepath)
        alert = json.load(f)
        f.close()
        uid = alert["uid"]
        try:
            self.api.alertingprovisioning.get_alertrule(uid)
            logging.info(f"Skipping alert: {alert.get('title')}")
        except GrafanaServerError or GrafanaClientError as err:
            if err.status_code == 404 or (
                err.status_code == 500 and "could not find alert rule" in err.message
            ):
                self.api.alertingprovisioning.create_alertrule(alert)
            else:
                logging.error(err.message)

    def import_contact_point(self, file: str) -> None:
        f = open(file)
        contact_point = json.load(f)
        f.close()
        uid = contact_point["uid"]
        contact_points = self.api.alertingprovisioning.get_contactpoints()
        for cp in contact_points:
            if cp["uid"] == uid:
                return None

        self.api.alertingprovisioning.create_contactpoint(contact_point)

    def import_notif_policy(self, file: str) -> None:
        f = open(file)
        notif_policy = json.load(f)
        f.close()
        curr_policy = self.api.alertingprovisioning.get_notification_policy_tree()
        if curr_policy["receiver"] != notif_policy["receiver"] or set(curr_policy["group_by"]) != set(notif_policy["group_by"]):
            self.api.alertingprovisioning.set_notification_policy_tree(notif_policy)
```

So, first I check if the resource already exists if so I'm skipping it, if not I create it. Once the uid is given I got the 500 error.

`grafana_client.client.GrafanaServerError: Server Error 500: could not find alert rule`

**Comment by jyepesr1** [comment]
btw, I'm running Grafana 9.2.1

**Comment by jyepesr1** [comment]
Ohh I realized about actually the API returns 500, so it's from our end, it's actually the Grafana API, so it's good!

**Comment by amotl** [comment]
Hi again,

grafana-client 3.2.0 has been released, including the contribution by @bursztyn-pl - thank you again!

@jyepesr1: Can I humbly ask you to also exercise some error paths, in order to evaluate if my change ebc2c0e0d did any harm to the overall implementation? Please let me know about it.

With kind regards,
Andreas.

**Comment by jyepesr1** [comment]
Hi @amotl,

I created some alerts and contact points to verify the behavior mentioned by @bursztyn-pl here

> Hello!
> First of all I am glad you find this contribution useful.
> answering your question…
> it’s not easy to answer now, because I don’t remember after one month :( I believe it was failing because grafana API (9.0.1 or 9.0.0) didn’t respond with any body/text in case of adding contact point or alert rule, the only response was status code so that I had to do quick fix.

Probably @bursztyn-pl is referring to when some endpoints like deleting an alert rule return a 204 which means no content and the body is empty https://grafana.com/docs/grafana/latest/developers/http_api/alerting_provisioning/#span-idroute-delete-alert-rulespan-delete-a-specific-alert-rule-by-uid-_routedeletealertrule_

**Comment by amotl** [comment]
Hi again,

oh I see the point now and it finally makes sense that @bursztyn-pl meant to add the corresponding change, in order to receive "204" to determine success? However, in this case, having an empty response is perfectly valid, right?

In another iteration, introducing a breaking change, we may adjust `def __request_runner` to return the full response object, in order to give more power to the user of the library, because then she would be able to get hold of _both_ the response body, and the status code.

On this matter, those code snippets could be simplified. What do you think about it?

https://github.com/panodata/grafana-client/blob/362bffd5ea07846831220f238bae1d6d27958183/grafana_client/client.py#L139-L142

https://github.com/panodata/grafana-client/blob/362bffd5ea07846831220f238bae1d6d27958183/grafana_client/client.py#L162-L165

So, by postponing this detail into the future, I think it will be safe to close this issue and think of this feature being completed successfully. Please raise your hand if you think otherwise.

With kind regards,
Andreas.

**Comment by jyepesr1** [comment]
Hi @amotl , actually we need to fix this issue with the 204, since if you try to delete we got 

```
Traceback (most recent call last):
  File "/home/jyepesr/SCB/grafana-importer/src/cli.py", line 87, in <module>
    main()
  File "/home/jyepesr/SCB/grafana-importer/src/cli.py", line 69, in main
    grafana.import_alerts(alert)
  File "/home/jyepesr/SCB/grafana-importer/src/grafana.py", line 114, in import_alerts
    self.api.alertingprovisioning.delete_alertrule(uid)
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.10/3.10.8/lib/python3.10/site-packages/grafana_client/elements/alertingprovisioning.py", line 58, in delete_alertrule
    r = self.client.DELETE(delete_alertrule_path)
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.10/3.10.8/lib/python3.10/site-packages/grafana_client/client.py", line 165, in __request_runner
    return r.json()
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.10/3.10.8/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by amotl** [comment]
OMG, you are right. Now I am seeing that @bursztyn-pl had a very good point here.

**Comment by amotl** [comment]
Can I ask you to tell me the value of the `Content-Type` response header in the case of 204 responses here?

**Comment by amotl** [comment]
Answering myself here.

```
$ http DELETE http://admin:admin@localhost:3000/api/v1/provisioning/alert-rules/Bwow6jH4k
```
```
HTTP/1.1 204 No Content
Cache-Control: no-cache
Content-Type: application/json
Date: Wed, 02 Nov 2022 03:54:05 GMT
Expires: -1
Pragma: no-cache
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-Xss-Protection: 1; mode=block
```

The `Content-Type` is still `application/json`. However, unmarshaling an empty string from JSON raises an exception, so it is a bit unfortunate.

**Comment by amotl** [comment]
Aha. It looks like users of HTTP client libraries must explicitly check for _204 No Content_ responses and handle them correspondingly. See also [1-3].

[1] https://www.rfc-editor.org/rfc/rfc9110.html#status.204
[2] https://github.com/psf/requests/blob/v2.28.1/docs/user/quickstart.rst#json-response-content
[3] https://github.com/Huachao/vscode-restclient/issues/598

**Comment by amotl** [comment]
#44 improves the situation. It has been released with grafana-client 3.2.1. Please let me know if this works for you now, or about any other issues you might observe. Thank you again!

**Comment by jyepesr1** [comment]
Hi @amotl ,

Sorry for the late response, I was afk.

Thank you so much, I'll make my own tests! And let you know here!

**Comment by Maharacha** [comment]
I'm really grateful for this added functionality, amazing work!

I have a question, not really related to this issue I guess though. Is there a way to make it possible to edit or delete the alert rule using the UI when creating it from the API? Since this is using the provisioning it's not possible to edit or delete it from the UI... What I'm doing now is to browse the alert rule in the UI to get the UID from the URL to then use this library to delete the alert rule. There must be a better way!

Thanks :)

**Comment by amotl** [comment]
> Is there a way to make it possible to edit or delete the alert rule using the UI when creating it from the API? Since this is using the provisioning it's not possible to edit or delete it from the UI.

Oh. I haven't been aware of that detail. Apologies that I do not have any answer to this. Maybe @bursztyn-pl or @jyepesr1 do?

**Comment by amotl** [comment]
Hi again,

on the Grafana forum, and its issue tracker, I found those resources regarding this topic:

- https://community.grafana.com/t/create-alerts-notification-policies-via-rest-api/67426
- https://community.grafana.com/t/cannot-save-alerting-rule-changes-when-alert-is-created-through-the-api/69987
- https://community.grafana.com/t/edit-alert-rule-in-the-ui-created-via-http-api/73553
- https://github.com/grafana/grafana/issues/51455

@JohnnyQQQQ responded on the issue referenced above:

> This is the expected behavior, as we don't allow to mix things up. Otherwise, they might end up in a strange place where you do changes in the UI but you might have some provisioning tooling running that will overwrite those changes.

With kind regards,
Andreas.

**Comment by jyepesr1** [comment]
Yeah, unfortunately there is no option yet from the UI. This is a limitation from Grafana.

**Comment by Maharacha** [comment]
Is it possible to use `/api/ruler/grafana/api/v1/rules/<rule_group>` instead? That is what the UI is using. When using that endpoint instead of the provisioning it is possible to edit and delete from the UI.

**Comment by amotl** [comment]
Dear Joakim,

thanks for your suggestion. I've diverted your post to #45 in order to handle it separately from this patch. I think both API resources should not be mixed up, in order not to confuse users. Saying that, I am always happy to extend `grafana-client` to any kinds of API calls into Grafana.

With kind regards,
Andreas.
